#!/bin/sh

# note: remove trailing slashes
indir="src"
outdir="pub"

defaultifs=${IFS}

main() {
	# Script Entry point
	cleanup
	genhtml
	addother
}

cleanup() {
	# cleanup
	rm -rf "${outdir}"
	mkdir -p "${outdir}"
}

genhtml() {
	# Generate html using pandoc
	IFS=$(printf '\n\b')
	# shellcheck disable=SC2044 # fixed problem by setting IFS above
	for i in $(find "${indir}" -name '*.md'); do
		outfname="${outdir}/$(basename "${i%.md}.html")"

		pandoc -f markdown -t html \
			--template="tpl/template.html" \
			--lua-filter="tpl/links-to-html.lua" \
			"${i}" -o "${outfname}"
	done

	IFS=${defaultifs}
}

addother() {
	cp -r "${indir}/assets" "${outdir}"
}

main "$@"
